//
//  HomeRouter.swift
//  Simple_App_Unit_Tests
//
//  Created by Alvaro Vinicius do Nascimento Fernandes on 03/12/19.
//  Copyright (c) 2019 Alvaro Vinicius do Nascimento Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func perfect()
    func tooClose()
    func notSoGood()
    func veryBad()
    func showError()
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: HomeRoutingLogic, HomeDataPassing {
    
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    var title: String = ""
    var message: String = ""
    
    func perfect() {
        title = "Perfect!"
        showAlert(title, message)
    }
    
    func tooClose() {
        title = "Too Close!"
        showAlert(title, message)
    }
    
    func notSoGood() {
        title = "It was good, don't give up"
        showAlert(title, message)
    }
    
    func veryBad() {
        title = "Not even close ..."
        showAlert(title, message)
    }
    
    func showError() {
        showAlert(title, message)
    }

    private func showAlert(_ title: String, _ message: String) {
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let action = UIAlertAction(title: "OK", style: .default) { (action) in
        }
        alert.addAction(action)
        viewController?.present(alert, animated: true, completion: nil)
    }
}
