//
//  HomeInteractor.swift
//  Simple_App_Unit_Tests
//
//  Created by Alvaro Vinicius do Nascimento Fernandes on 03/12/19.
//  Copyright (c) 2019 Alvaro Vinicius do Nascimento Fernandes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol HomeBusinessLogic {
    var getValue: Int { get }
    func load(_ value: Int, _ target: Int)
}

protocol HomeDataStore {
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    
    var presenter: HomePresentationLogic?
    
    var getValue: Int {
        return Int.random(in: 0 ..< 100)
    }
    
    func load(_ value: Int, _ target: Int) {
        
        let diferrence = abs(target - value)
        
        switch diferrence {
        case 0:
            presenter?.perfect()
        case 1 ..< 6:
            presenter?.tooClose()
        case 6 ..< 11:
            presenter?.notSoGood()
        case 11 ..< 100:
            presenter?.veryBad()
        default:
            presenter?.showError()
        }

    }
    
}
